steps:
  # build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/ute-nlp-absa/absa-repo/absa-train:$SHORT_SHA', '.']

  # push the image to Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/ute-nlp-absa/absa-repo/absa-train:$SHORT_SHA']

# to just show logs, not save them
options:
  logging: CLOUD_LOGGING_ONLY
