steps:
  # 1. Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/ute-nlp-absa/absa-repo/absa-train:1.0', '.']

  # 2. Push the image to Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/ute-nlp-absa/absa-repo/absa-train:1.0']

# 3. THIS IS THE FIX: Tell Google to just show logs, not save them
options:
  logging: CLOUD_LOGGING_ONLY
